spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cloud_user?useSSL=false
    username: root
    password: 1234
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  type-aliases-package: com.wan.user.pojo
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    com.wan: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS

feign:
  hystrix:
    enabled: true

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 2000 #设置hystrix的超时时间为1000ms
      circuitBreaker:
        #在当10秒的时间内，最近10次调用请求，请求错误率超过50%，则触发熔断5秒，期间快速失败，以下都是默认值
        requestVolumeThreshold: 10
        errorThresholdPercentage: 50
        sleepWindowInMilliseconds: 5000
      #设置统计的时间窗口值的毫秒值，circuit break 的打开会根据1个rolling window的统计来计算。
      #若rolling window被设为10000毫秒，则rolling window会被分成n个buckets，
      #每个bucket包含success，failure，timeout，rejection的次数的统计信息。默认10000。
      metrics:
        rollingStats:
          #rolling window大小设置
          timeInMilliseconds: 10000
          #分的buckets的数量
          numBuckets: 10






